name: CI/CD Workflow

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into your server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          
      - name: Change directory to /home/ubuntu/dev/backend
        run: cd ~/dev/backend
        
      - name: Pull changes from development branch
        run: |
          git pull origin development

      - name: Reload PM2
        run: |
          pm2 reload all

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
