import { IStudent } from '../interface/IStudents';
 
export const studentsData: IStudent[] = [
  {
    prefix: 'Mr',
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    phone: '1234567890',
    address: '123 Main Street',
    city: 'Mumbai',
    pincode: '400001',
    dob: new Date('1995-08-15'),
    age: 26,
    photo: 'photo-url',
    schoolName: 'ABC School',
    studentClass: '10th',
    schoolCity: 'Mumbai',
    schoolAddress: '456 School Avenue',
    schoolPincode: '400002',
    other: {},
  },
  {
    prefix: 'Ms',
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    phone: '9876543210',
    address: '789 Park Road',
    city: 'Delhi',
    pincode: '110001',
    dob: new Date('1998-05-20'),
    age: 23,
    photo: 'photo-url',
    schoolName: 'XYZ School',
    studentClass: '12th',
    schoolCity: 'Delhi',
    schoolAddress: '111 School Street',
    schoolPincode: '110002',
    other: {},
  },
  {
    prefix: 'Ms',
    firstname: 'Emma',
    lastname: 'Johnson',
    email: 'emma.johnson@example.com',
    phone: '7865432190',
    address: '555 River View',
    city: 'Bangalore',
    pincode: '560001',
    dob: new Date('1997-10-10'),
    age: 24,
    photo: 'photo-url',
    schoolName: 'PQR School',
    studentClass: '11th',
    schoolCity: 'Bangalore',
    schoolAddress: '222 School Lane',
    schoolPincode: '560002',
    other: {},
  },
  // Add more student objects here
];
  